apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage_tf_s3_template
  description: A template for creating and managing Terraform modules in [backstage.io](https://www.backstage.io/)
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: mryutran/backstage_tf_s3_template
spec:
  type: service
  owner: mryutran
  lifecycle: production