apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.name }}
  description: {{ cookiecutter.description }}
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: mryutran/{{ cookiecutter.repo_name }}
spec:
  type: service
  owner: {{ cookiecutter.owner }}
  lifecycle: production
  providesApis:
    - {{ cookiecutter.name }}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {{ cookiecutter.name }}
  description: {{ cookiecutter.description }}
spec:
  type: internal
  lifecycle: production
  owner: mryutran
  definition: "{{ cookiecutter.description }}"